
logger:
  json: true
  stdout: true
  file:
    name: 'logs/agent.log'
    max_size: 50
    max_backup: 100
    max_age: 31
    compressed: true
  level: 'debug'

server:
  http:
    timeout: 6
    # hmac_header: ''
    # hmac_secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    bearer_token: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
    jwt:
      secret: 'ab2316584873095f017f6dfa7a9415794f563fcc473eb3fe65b9167e37fd5a4b'
      access_token_exp: 1
      refresh_token: true
      refresh_token_exp: 10
    allowed_origins: '*'
    allowed_headers: 'X-Requested-With,Content-Type,Authorization'
    allowed_methods: 'GET,POST,PUT,DELETE,HEAD'

  repo:
    driver: 'pgx'
    conn_str: 'host=testpghost user=test password=test123 dbname=woong_order port=5432 sslmode=disable TimeZone=Asia/Seoul'
    # used when driver is oci8, postgres, mssql...
    max_idle_conns: 5
    max_open_conns: 25
    conn_max_lifetime_in_min: 15

client:
  cookies:
    id_token:
      name: 'id_token'
      expires: 604800
      same_site: 'strict'
      domain: 'my-domain.com'
      path: '/'
  oauth2:
    integrated:
      openid_conf_url: 'https://127.0.0.1:5558/.well-known/openid-configuration'


  user_grpc:
    addr: 'localhost:42001,localhost:42001'
    keep_alive:
      time: 60
      timeout: 1
      permit_without_stream: true

    resolver_scheme: 'user'
    resolver_service_name: 'user-service'
    default_service_config: >
      {"loadBalancingConfig": [{"round_robin":{}}],
        "methodConfig": [{
          "name": [{}],
          "waitForReady": true,
          "retryPolicy": {
            "MaxAttempts": 3,
            "InitialBackoff": ".01s",
            "MaxBackoff": ".01s",
            "BackoffMultiplier": 1.0,
            "RetryableStatusCodes": [ "UNAVAILABLE" ]
          }
        }]
      }
    ca_cert_pem: './certs/server.crt'
    cert_server_name: 'localhost'
    dial_block: false
    dial_timeout: 3